server:
  port: 8081
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?characterEncoding=utf8&useUnicode=true&verifyServerCertificate=false&useSSL=false&requireSSL=false&serverTimezone=UTC
    username: root
    password: root


mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  type-aliases-package: com.guanghui.entity
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句

eureka:
  client:
    #将自身注册进eurekaserver
    register-with-eureka: true
    #从eurekaserver抓取已注册的服务信息，默认位true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka8002.com:8002/eureka/
  instance:
    instance-id: payment8081
    prefer-ip-address: true

logging:
  file:
    name: payment.out
    path: ./logs
    max-size: 100MB
    max-history: 7
  level:
    root: info
  config: classpath:logback-spring.xml