server:
  port: 80
spring:
  application:
    name: cloud-order-service


eureka:
  client:
    #将自身注册进eurekaserver
    register-with-eureka: true
    #从eurekaserver抓取已注册的服务信息，默认位true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka8002.com:8002/eureka/
  instance:
    instance-id: order80
    prefer-ip-address: true

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true #支持重试所有请求  false只重试get请求
  restclient:
    enabled: true